apiVersion: v1
kind: Pod
metadata:
  name: restricted-pod
  labels:
    app: restricted-pod
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    capabilities:
      drop:
        - ALL
  containers:
  - name: main
    image: busybox:latest
    command: ["sleep", "3600"]
  securityContext:
    capabilities:
      add:
        - NET_BIND_SERVICE