apiVersion: v1
kind: Pod
metadata:
  name: secure-pod
  labels:
    app: secure-pod
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
  containers:
  - name: main
    image: busybox:latest
    command: ["sleep", "3600"]