apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terraform-cloud-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: <YOUR_GIT_REPOSITORY_URL>
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false