apiVersion: v1
kind: Pod
metadata:
  name: my-app-pod
spec:
  volumes:
    - name: my-data
      persistentVolumeClaim:
        claimName: local-pvc
  containers:
    - name: my-app-container
      image: busybox:latest
      command: ["/bin/sh", "-c", "while true; do echo $(date) >> /data/data.txt; sleep 5; done"]
      volumeMounts:
        - name: my-data
          mountPath: /data