"""
Lab File Creator Module
=======================
Creates the lab directory structure and files
from a GeneratedLab object.
"""

import os
import re
from pathlib import Path
from typing import Optional
from datetime import datetime

from ai_generator import GeneratedLab


# Difficulty badges for README (necessary to indicate difficulty visually)
DIFFICULTY_BADGES = {
    'easy': '![Difficulty: Easy](https://img.shields.io/badge/Difficulty-Easy-brightgreen)',
    'medium': '![Difficulty: Medium](https://img.shields.io/badge/Difficulty-Medium-yellow)',
    'hard': '![Difficulty: Hard](https://img.shields.io/badge/Difficulty-Hard-red)',
}

# Technology badges
TECH_BADGES = {
    'docker': '![Docker](https://img.shields.io/badge/Docker-2496ED?logo=docker&logoColor=white)',
    'kubernetes': '![Kubernetes](https://img.shields.io/badge/Kubernetes-326CE5?logo=kubernetes&logoColor=white)',
    'helm': '![Helm](https://img.shields.io/badge/Helm-0F1689?logo=helm&logoColor=white)',
    'argocd': '![ArgoCD](https://img.shields.io/badge/ArgoCD-EF7B4D?logo=argo&logoColor=white)',
    'ansible': '![Ansible](https://img.shields.io/badge/Ansible-EE0000?logo=ansible&logoColor=white)',
}


def sanitize_slug(slug: str) -> str:
    """Ensure slug is valid for directory names"""
    # Remove special characters, keep only alphanumeric and hyphens
    slug = re.sub(r'[^a-z0-9-]', '-', slug.lower())
    # Remove multiple consecutive hyphens
    slug = re.sub(r'-+', '-', slug)
    # Remove leading/trailing hyphens
    slug = slug.strip('-')
    return slug[:50]  # Max 50 chars


def get_next_lab_number(base_path: Path) -> int:
    """Get the next available lab number"""
    existing_labs = list(base_path.glob('lab-*'))
    if not existing_labs:
        return 1

    numbers = []
    for lab_dir in existing_labs:
        match = re.match(r'lab-(\d+)', lab_dir.name)
        if match:
            numbers.append(int(match.group(1)))

    return max(numbers, default=0) + 1


def generate_readme(lab: GeneratedLab, lab_number: int) -> str:
    """Generate a comprehensive README.md for the lab"""

    difficulty_badge = DIFFICULTY_BADGES.get(lab.difficulty, DIFFICULTY_BADGES['medium'])
    tech_badge = TECH_BADGES.get(lab.technology, '')

    # Build objectives list
    objectives_md = '\n'.join(f'- {obj}' for obj in lab.objectives)

    # Build prerequisites list
    prereqs_md = '\n'.join(f'- {prereq}' for prereq in lab.prerequisites)

    # Build steps
    steps_md = ''
    for i, step in enumerate(lab.steps, 1):
        steps_md += f"\n### Step {i}: {step.get('title', f'Step {i}')}\n\n"
        steps_md += step.get('content', '')
        steps_md += '\n'

    # Build hints (collapsible)
    hints_md = ''
    if lab.hints:
        hints_md = '\n<details>\n<summary> Hints (click to expand)</summary>\n\n'
        for i, hint in enumerate(lab.hints, 1):
            hints_md += f'{i}. {hint}\n'
        hints_md += '\n</details>\n'

    # Build solution notes (collapsible)
    solution_md = ''
    if lab.solution_notes:
        solution_md = '\n<details>\n<summary>✅ Solution Notes (spoiler)</summary>\n\n'
        solution_md += lab.solution_notes
        solution_md += '\n\n</details>\n'

    readme = f"""# Lab {lab_number:02d}: {lab.title}

{difficulty_badge} {tech_badge}

> **Auto-generated lab** - Created on {datetime.now().strftime('%Y-%m-%d')}

## Description

{lab.description}

## Learning Objectives

{objectives_md}

## Prerequisites

{prereqs_md}

## Lab Steps
{steps_md}
{hints_md}
{solution_md}

---

## Notes

- **Difficulty:** {lab.difficulty.capitalize()}
- **Estimated time:** {'30-45' if lab.difficulty == 'easy' else '45-75' if lab.difficulty == 'medium' else '75-90'} minutes
- **Technology:** {lab.technology.capitalize()}

##  Cleanup

Don't forget to clean up resources after completing the lab:

```bash
# Example cleanup commands (adjust based on lab content)
docker system prune -f
# or
kubectl delete -f .
# or
helm uninstall <release-name>
```

---

*This lab was auto-generated by the [Lab Generator Bot](../.github/workflows/generate-lab.yml)*
"""

    return readme


class LabFileCreator:
    """Creates lab files and directories from GeneratedLab objects"""

    def __init__(self, base_path: Optional[str] = None):
        """Initialize with base path for labs"""
        if base_path:
            self.base_path = Path(base_path)
        else:
            # Default: parent of scripts directory
            self.base_path = Path(__file__).parent.parent

    def create_lab(self, lab: GeneratedLab) -> Path:
        """Create a complete lab directory with all files"""

        # Get next lab number
        lab_number = get_next_lab_number(self.base_path)

        # Sanitize slug
        slug = sanitize_slug(lab.slug)

        # Create directory name
        lab_dir_name = f"lab-{lab_number:02d}-{slug}"
        lab_path = self.base_path / lab_dir_name

        print(f"📁 Creating lab directory: {lab_dir_name}")

        # Create the directory
        lab_path.mkdir(parents=True, exist_ok=True)

        # Generate and write README.md (override AI-generated if exists)
        readme_content = generate_readme(lab, lab_number)
        readme_path = lab_path / 'README.md'
        readme_path.write_text(readme_content, encoding='utf-8')
        print(f"   ✅ Created: README.md")

        # Write all other files from the lab
        for filename, content in lab.files.items():
            # Skip README.md as we generated our own
            if filename.lower() == 'readme.md':
                continue

            file_path = lab_path / filename

            # Create parent directories if needed (for nested files)
            file_path.parent.mkdir(parents=True, exist_ok=True)

            # Write the file
            file_path.write_text(content, encoding='utf-8')
            print(f"   ✅ Created: {filename}")

        # Create a metadata file for tracking
        metadata = {
            'title': lab.title,
            'technology': lab.technology,
            'difficulty': lab.difficulty,
            'generated_at': datetime.now().isoformat(),
            'objectives': lab.objectives,
        }

        import json
        metadata_path = lab_path / '.lab-metadata.json'
        metadata_path.write_text(json.dumps(metadata, indent=2), encoding='utf-8')
        print(f"   ✅ Created: .lab-metadata.json")

        print(f"✅ Lab created successfully: {lab_path}")

        return lab_path

    def get_existing_labs(self) -> list[str]:
        """Get list of existing lab directory names"""
        labs = []
        for item in self.base_path.iterdir():
            if item.is_dir() and item.name.startswith('lab-'):
                labs.append(item.name)
        return sorted(labs)


# Standalone test
if __name__ == "__main__":
    from ai_generator import GeneratedLab

    # Create a test lab
    test_lab = GeneratedLab(
        title="Test Docker Multi-stage Build",
        slug="test-docker-multistage",
        technology="docker",
        difficulty="medium",
        description="Learn to optimize Docker images using multi-stage builds.",
        objectives=[
            "Understand multi-stage build concept",
            "Reduce image size by 80%",
            "Apply best practices"
        ],
        prerequisites=[
            "Docker installed",
            "Basic Dockerfile knowledge"
        ],
        steps=[
            {
                "title": "Create a basic Dockerfile",
                "content": "First, create a simple Dockerfile:\n\n```dockerfile\nFROM node:18\nWORKDIR /app\nCOPY . .\nRUN npm install\nCMD [\"node\", \"server.js\"]\n```"
            },
            {
                "title": "Optimize with multi-stage",
                "content": "Now let's optimize:\n\n```dockerfile\nFROM node:18 AS builder\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci\n\nFROM node:18-slim\nWORKDIR /app\nCOPY --from=builder /app/node_modules ./node_modules\nCOPY . .\nCMD [\"node\", \"server.js\"]\n```"
            }
        ],
        files={
            "Dockerfile": "FROM node:18\nWORKDIR /app\nCOPY . .\nRUN npm install\nCMD [\"node\", \"server.js\"]",
            "package.json": '{"name": "test", "version": "1.0.0"}'
        },
        hints=[
            "Use slim or alpine base images for smaller size",
            "Only copy what you need in the final stage"
        ],
        solution_notes="Multi-stage builds allow you to use multiple FROM statements."
    )

    creator = LabFileCreator()
    print(f"\nExisting labs: {creator.get_existing_labs()}")

    # Uncomment to test creation:
    # lab_path = creator.create_lab(test_lab)
    # print(f"\nCreated test lab at: {lab_path}")
